# Generated by Django 5.2.6 on 2025-10-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='qr_code_id',
        ),
    ]
