# Generated by Django 5.2.6 on 2025-10-02 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_qr_code_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='questions', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='patients.question'),
        ),
    ]
